server:
  port: 8012
device-server:
  netty:
    #测试暂时用8888，生产环境用9999
    port: 8888
    url: 127.0.0.1
spring:
  profiles: dev
  application:
    name: start-device-server
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@(description=(address_list= (address=(host=172.16.100.12)(protocol=tcp)(port=1521))(address=(host=172.16.100.13)(protocol=tcp)(port=1521))(load_balance=yes)(failover=yes))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = iafc)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 180)(DELAY = 15))))
    username: iafc_unionpay
    password: unionpaypro
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  typeAliasesPackage: cn.wimetro
logging:
#  level:
#    com.baomidou.mybatisplus.samples: debug
#  file: E:\myserver\log\cloudLog.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
#  instance:
#    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
#    lease-renewal-interval-in-seconds: 1
#    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
#    lease-expiration-duration-in-seconds: 2

