server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      #注册另一台机器的ip，端口
      defaultZone: http://127.0.0.1:8762/eureka/
  server:
    #关闭自我保护
    enable-self-preservation: false
#    #清理间隔
#    eviction-interval-timer-in-ms: 5000
