server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: dev
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    #关闭自我保护
    enable-self-preservation: false
#    #清理间隔
#    eviction-interval-timer-in-ms: 5000
